### ISSUE TITLE
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by MahsaPaknezhad** [aleksispi/drl-rpn-tf#3]
Hi!

I have cuda-10.0 installed on my system with a GPU RTX 2070. I modified the setup.py file in the faster-rcnn directory, set -arch = sm_75, and built the Cython modules. The demo.py for the faster-rcnn runs without any errors. However, when I run the trainval_net.py code, I get the following error:

Traceback (most recent call last):
  File "/home/mahsa/Documents/DRL_RPN/drl-rpn-tf/tools/trainval_net.py", line 13, in <module>
    from model.train_val import get_training_roidb, train_net
  File "/home/mahsa/Documents/DRL_RPN/drl-rpn-tf/tools/../lib/model/train_val.py", line 31, in <module>
    from model.factory import run_drl_rpn
  File "/home/mahsa/Documents/DRL_RPN/drl-rpn-tf/tools/../lib/model/factory.py", line 25, in <module>
    from model.nms_wrapper import nms
  File "/home/mahsa/Documents/DRL_RPN/drl-rpn-tf/tools/../lib/model/nms_wrapper.py", line 12, in <module>
    from nms.gpu_nms import gpu_nms
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

Process finished with exit code 1
I am not sure why it is looking for cuda-8 on my system. Can you please help me with this problem?

**Comment by aleksispi** [comment]
Hi,

I have not run stuff using CUDA-10. It appears your problem should happen also in the original Faster R-CNN code base (https://github.com/endernewton/tf-faster-rcnn), on top of which I implemented drl-RPN, since it contains exactly the same nms_wrapper.py code (https://github.com/endernewton/tf-faster-rcnn/blob/master/lib/model/nms_wrapper.py). I unfortunately cannot help you with this libcudart issue, but perhaps the authors of the aforementioned repo knows something. And please, if you figure it out, post it here so anyone else using CUDA-10 may know what to do. Best of luck with this!

Cheers,
Aleksis

**Comment by MahsaPaknezhad** [comment]
I made sure LD_LIBRARY_PATH is pointing to my cuda-10.0 and re-compiled all the code using python2.7. This, however, was not the problem because I was still getting ImportError:  libcudart.so.8.0 error. I figured that one of the files the code was looking for was not in the expected directory. After adding the file the code ran without error.

**Comment by aleksispi** [comment]
Thanks for coming back on this Mahsa! I'm glad it worked out!
